cmip6restapi_url: http://esg-dn1.nsc.liu.se/esg-search/search
base_data_dir: /export/data/aschwanden/cmip6

max_download_attempts: 3

dir_filename_regex: 
- tos: ^tos
  ts: ^ts
  tas: ^tas
  fgco2: ^fgco2
  dissic: ^dissic
  talk: ^talk
  thetao: ^thetao
  areacella: ^areacella
  areacello: ^areacello

- day: day_
  month: (mon_|monAnt|monGre)
  year: yr_

- 1pctCO2: 1pctCO2
  historical: historical
  piControl: piControl
  ssp126: ssp126
  ssp245: ssp245
  ssp245-GHG: ssp245-GHG
  ssp245-nat: ssp245-nat
  ssp370: ssp370
  ssp585: ssp585

- AWI-CM-1-1-MR: AWI-CM-1-1-MR
  BCC-CSM2-MR: BCC-CSM2-MR
  BCC-ESM1: BCC-ESM1
  CESM2: CESM2
  CESM2-WACCM: CESM2-WACCM
  CMCC-CM2-HR4: CMCC-CM2-HR4
  CMCC-CM2-VHR4: CMCC-CM2-VHR4
  CNRM-CM6-1: CNRM-CM6-1
  CNRM-ESM2-1: CNRM-ESM2-1
  CanESM5: CanESM5
  E3SM-1-0: E3SM-1-0
  EC-Earth3: EC-Earth3
  EC-Earth3-Veg: EC-Earth3-Veg
  ECMWF-IFS-HR: ECMWF-IFS-HR
  ECMWF-IFS-LR: ECMWF-IFS-LR
  FGOALS-f3-L: FGOALS-f3-L
  GFDL-AM4: GFDL-AM4
  GFDL-CM4: GFDL-CM4
  GISS-E2-1-G: GISS-E2-1-G
  GISS-E2-1-H: GISS-E2-1-H
  HadGEM3-GC31-HM: HadGEM3-GC31-HM
  HadGEM3-GC31-LM: HadGEM3-GC31-LM
  HadGEM3-GC31-MM: HadGEM3-GC31-MM
  IPSL-CM6A-ATM-HR: IPSL-CM6A-ATM-HR
  IPSL-CM6A-LR: IPSL-CM6A-LR
  MIROC6: MIROC6
  MPI-ESM1-2-HR: MPI-ESM1-2-HR
  MRI-ESM2-0: MRI-ESM2-0
  NICAM16-7S: NICAM16-7S
  SAM0-UNICON: SAM0-UNICON
  UKESM1-0-LL: UKESM1-0-LL
