# Base CMIP6 search API URL
cmip6restapi_url: http://esg-dn1.nsc.liu.se/esg-search/search
# Directory where all downloaded data is stored
base_data_dir: /export/data/model_data/cmip6

# Number of download attempts before the download is aborted.
max_download_attempts: 1
# Number of parallel downloads
n_worker: 10

# Google credentials file
google_credentials_file: /home/aschwanden/.config/cmip6download/gcreds.json
# Google calc sheet name
google_sheet_path: cmip6download_status

# Minimum number of members. If no members are found, a new
# search is conducted with no members specified. From
# all the found members from this search the first X 
# members are downloaded.
min_number_of_members: 1

# Maximum number of members. If more members are found only 
# the first X members are downloaded.
max_number_of_members: 2
